services:
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    platform: linux/amd64
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"

  postgres:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres
    environment:
      - POSTGRES_USER=trips
      - POSTGRES_PASSWORD=trips
      - POSTGRES_DB=trips
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: api
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TRIPS_TOPIC=trips.raw
      - PUBLISH_DELAY_SECONDS=0.5
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=trips
      - POSTGRES_USER=trips
      - POSTGRES_PASSWORD=trips
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres

  spark-master:
    image: apache/spark:3.5.1
    platform: linux/amd64
    container_name: spark-master
    hostname: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/opt/spark-data
      - ./src:/opt/spark-apps

  spark-worker:
    image: apache/spark:3.5.1
    platform: linux/amd64
    container_name: spark-worker
    command:
      - "/opt/spark/bin/spark-class"
      - "org.apache.spark.deploy.worker.Worker"
      - "spark://spark-master:7077"
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
      - ./src:/opt/spark-apps

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    container_name: airflow-webserver
    command: ["webserver"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://trips:trips@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Recife
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=America/Recife
      - DELTA_BASE_PATH=/opt/spark-data/delta
      - CHECKPOINT_BASE_PATH=/opt/spark-data/checkpoints
      - MAX_OFFSETS_PER_TRIGGER=10
      - MAX_FILES_PER_TRIGGER=1
    volumes:
      - ./data/airflow:/opt/airflow
      - ./data:/opt/spark-data
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow.Dockerfile
    container_name: airflow-scheduler
    command: ["scheduler"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://trips:trips@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Recife
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=America/Recife
      - DELTA_BASE_PATH=/opt/spark-data/delta
      - CHECKPOINT_BASE_PATH=/opt/spark-data/checkpoints
      - MAX_OFFSETS_PER_TRIGGER=10
      - MAX_FILES_PER_TRIGGER=1
    volumes:
      - ./data/airflow:/opt/airflow
      - ./data:/opt/spark-data
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    depends_on:
      - airflow-webserver
      - postgres

volumes:
  postgres_data:
